
server:
  error:
    include-message: always
spring:
  liquibase:
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5433/Appointment
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

