#spring:
#  liquibase:
#    enabled: true
#
#  datasource:
#    url: jdbc:postgresql://localhost:5432/Doctor_Appointment
#    username: postgres
#    password: serhii
#    driver-class-name: org.postgresql.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: none
#    database: postgresql
#    show-sql: true

server:
  port: 9090
spring:
  liquibase:
    enabled: false
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    show-sql: true

  h2:
    console:
      enabled: true



